server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sulsul
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        bucket: ${BUCKET}
      credentials:
        access-key: ${ACCESSKEY}
        secret-key: ${SECRETKEY}
      region:
        static: ${REGION}
        auto: false
      stack:
        auto: false

# Failed to connect to service endpoint 무시
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error