spring:
  profiles:
    default: dev


cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: sulsul-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


s3:
  host:
    name: https://sulsul-bucket.s3.ap-northeast-2.amazonaws.com/
