server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /api-docs

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error # Failed to connect to service endpoint 에러 무시