server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sulsul
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false

s3:
  host:
    name: https://${BUCKET}.s3.${REGION}.amazonaws.com/

# Failed to connect to service endpoint 무시
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error