spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/sulsul
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${URL}
#    username: ${USERNAME}
#    password: ${USERPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true


domain:
  name: http://www.localhost:8081