server:
  port: 8080

spring:
  config:
    use-legacy-processing: true

  include:
    - security
    - oauth
    - s3
    - fcm
    - redis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

springdoc:
  packages-to-exclude: "com.example.sulsul.health"
  swagger-ui:
    path: /api-docs

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error # Failed to connect to service endpoint 에러 무시

domain:
  name: https://takgyun.shop