spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false

s3:
  host:
    name: https://${BUCKET}.s3.${REGION}.amazonaws.com/

domain:
  name: http://www.localhost:8081

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error