name: deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Create fcm admin sdk file
        run: |
          cd ./src/main/resources
          mkdir -p fcm && cd fcm
          echo ${{ secrets.FCM_ADMIN_SDK }} >> ./sulsul-1c69a-firebase-adminsdk-eccp7-b17f75a0da.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image & Push to Docker Hub
        run: |
          docker build . -t junek3/sulsul-server
          docker build ./nginx -t junek3/sulsul-nginx
          docker push junek3/sulsul-server
          docker push junek3/sulsul-nginx

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: sulsul-beanstalk
          environment_name: Sulsul-beanstalk-env
          version_label: deploy-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ./docker-compose.yml